volumes:
  db_data:

services:
 db:
   image: postgres:15
   hostname: db
   env_file:
     - ./.env
   networks:
     - app_network
   environment:
     - TZ=Asia/Tokyo
     - POSTGRES_DB=$DB_NAME
     - POSTGRES_USER=$DB_USER
     - POSTGRES_PASSWORD=$DB_PASS
     - PGDATA=/var/lib/postgresql/data/pgdata
   ports:
     - 5432:5432
   volumes:
     - db_data:/var/lib/postgresql/data
     - ./sql:/docker-entrypoint-initdb.d

networks:
 app_network:
   driver: bridge